apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: new-go-test-srecref
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-go-test-srecref 
  name: new-go-test-srecref
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: new-go-test-srecref 
